'use server';
import { and, eq } from 'drizzle-orm';
import { storefrontCollectionProductSchema, storefrontCollectionSchema, uuid } from '@/lib/schemas';
import { db } from '../db/client';
import { products, storefrontCollectionProducts, storefrontCollections } from '../db/schema';
import { logActivity } from '../services/posting';
import { ActionError, writeAction } from './client';

export const createStorefrontCollection = writeAction.metadata({ action: 'created', entity: 'storefront_collection' }).inputSchema(storefrontCollectionSchema).action(async ({ parsedInput: input, ctx }) => db.transaction(async (tx) => { const [row] = await tx.insert(storefrontCollections).values(input).returning({ id: storefrontCollections.id, name: storefrontCollections.name }); if (!row) throw new ActionError('Could not create the collection.'); await logActivity(tx, { memberId: ctx.member.id, action: 'created storefront collection', entityType: 'storefront_collection', entityId: row.id, entityLabel: row.name }); return row; }));
export const addProductToStorefrontCollection = writeAction.metadata({ action: 'updated', entity: 'storefront_collection' }).inputSchema(storefrontCollectionProductSchema).action(async ({ parsedInput: input, ctx }) => db.transaction(async (tx) => { const [product] = await tx.select({ id: products.id }).from(products).where(eq(products.id, input.productId)).limit(1); if (!product) throw new ActionError('That product no longer exists.'); await tx.insert(storefrontCollectionProducts).values(input).onConflictDoUpdate({ target: [storefrontCollectionProducts.collectionId, storefrontCollectionProducts.productId], set: { position: input.position } }); await logActivity(tx, { memberId: ctx.member.id, action: 'assigned product to storefront collection', entityType: 'storefront_collection', entityId: input.collectionId, entityLabel: input.productId }); return input; }));
export const removeProductFromStorefrontCollection = writeAction.metadata({ action: 'updated', entity: 'storefront_collection' }).inputSchema(storefrontCollectionProductSchema.pick({ collectionId: true, productId: true })).action(async ({ parsedInput: input, ctx }) => db.transaction(async (tx) => { await tx.delete(storefrontCollectionProducts).where(and(eq(storefrontCollectionProducts.collectionId, input.collectionId), eq(storefrontCollectionProducts.productId, input.productId))); await logActivity(tx, { memberId: ctx.member.id, action: 'removed product from storefront collection', entityType: 'storefront_collection', entityId: input.collectionId, entityLabel: input.productId }); return input; }));
